<?php
/**
 * Learn content
 */
return [
    [
        'id'               => '1',
        'fk_category_id'   => '1',
        'title_thai'       => 'Bridging the Talent Gap – APC Lays the First Research Brick in South East Asia',
        'title_english'    => 'Bridging the Talent Gap – APC Lays the First Research Brick in South East Asia',
        'content_thai'     => [
            '<p><span style="color: #404040; white-space: pre-wrap;">That good talents make an organisation sounds like a tired truism, and in the philanthropy and social sector too organisations are cognisant that they need to assemble a team of professionals with expertise and interest so as to implement and fulfil their philanthropic aspirations. &nbsp;Yet there appears to be a mismatch: Potential candidates (or &ldquo;the supply&rdquo;) are reporting challenges in the recruitment, integration, and retention phases, while the philanthropic organisations (or &ldquo;the demand&rdquo;) have had difficulties identifying these talents at the senior level.</span></p>
            <p><span><strong><span style="font-size: 12pt; color: #404040; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Defining the key characteristics of what makes a leader in this sector</span></strong></span></p>
            <p><span style="color: #404040; white-space: pre-wrap;">What has emerged as critical to bridge this talent gap &ndash; after a research study conducted by Asia Philanthropy Circle (APC), based on 20 high-level interviews with a mix of potential candidates and philanthropic organisations who represent the five South East Asian countries of Indonesia, Malaysia, the Philippines, Singapore, and Thailand &ndash; is the need to define an industry standard on what a good candidate for an executive management position in a philanthropic organisation looks like. &nbsp;With a focus on the executive directors (ED) and the chief executive officers (CEO) of these organisations, perspectives on both the problems and the corresponding recommendations are highlighted.</span></p>
            <p><span style="color: #404040; white-space: pre-wrap;">Some of these problems may not be surprising, but this study is one of the first concerted efforts in the region to systematically research and document findings, so as to generate impetus for collective action. &nbsp;Pay and compensation, as well as the availability of career development pathways for mid- to senior-level candidates, emerged as the key considerations for potential candidates. Overall the respondents also pointed to limited recruiting scope and board governance as issues, though the finding that recruiters often disregarded the non-profit experience of potential candidates might be interesting for some.</span></p>
            <p><span><strong><span style="font-size: 12pt; color: #404040; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Top 10 recommendations for organisation &amp; sector</span></strong></span></p>
            <p><span style="color: #404040; white-space: pre-wrap;">10 recommendations are proposed in response, and APC is committed to take the lead by crafting a &ldquo;competency framework&rdquo; with fellow industry stakeholders that will help set a benchmark for reference, and by catalysing an exchange or fellowship programme.</span></p>
            <p><span style="color: #404040; white-space: pre-wrap;">Some of other eight recommendations can be adopted by organisations internally and put to effect expeditiously &ndash; such as &ldquo;transition programmes&rdquo; for potential candidates making a jump from other sectors, the adoption of valuable approaches such as benchmarking HR practices with the SME sector, as well as strengthening the development of senior management &ndash; though others require sector-wide reforms and mind-set changes. &nbsp;Among these industry-wide recommendations include the sharing of case studies or &ldquo;good-in-class&rdquo; HR practices, the creation of a South East Asian database of executive pay and compensation, as well as advocacy for board improvements. The work involved in the individual and collective implementation of each recommendation is substantial, yet necessary.</span></p>
            <p><span><strong><span style="font-size: 12pt; color: #404040; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">The work begins: convening the sector to move things forward</span></strong></span></p>
            <p><span style="color: #404040; white-space: pre-wrap;">&ldquo;Bridging the talent gap&rdquo;, in other words, is but the first research brick that APC is laying for the philanthropy and social sector in South East Asia. &nbsp;With this first step, APC &ndash; informed by the interests of its members &ndash; is committed to mobilise the contributions of relevant and valued partners, to effectively create a sustained momentum to advance the level of professionalism in the sector so as to grow social impact in the region. &nbsp;Far too often, philanthropists and non-profit professionals in the region run ahead of their capacity to implement and fulfil their philanthropic aspirations, and in the process pay too little attention to the overall talent deficits in the sector.</span></p>
            <p><span style="color: #404040; white-space: pre-wrap;">A long-term goal, in this vein, is to actualise the vision &ndash; or truism &ndash; of empowering potential candidates and philanthropic organisations in the philanthropy and social sector to be matched more effectively, first and foremost by defining an industry standard on what a good ED or CEO looked like, and in addition, what a good organisation looked like. &nbsp;This will take time and effort, though the investment will be well worth it.</span></p>
            <p><span><em><span style="font-size: 12pt; color: #404040; white-space: pre-wrap;">*Jinyao is the researcher and author for the report: Bridging the Talent Gap, which will be launched soon with members and industry leaders.</span></em></span></p>
            <p><span style="color: #404040; white-space: pre-wrap;"><em>By Kwan Jinyao</em></span></p>',
        ],
        'content_english'  => [
            '<p><span style="color: #404040; white-space: pre-wrap;">That good talents make an organisation sounds like a tired truism, and in the philanthropy and social sector too organisations are cognisant that they need to assemble a team of professionals with expertise and interest so as to implement and fulfil their philanthropic aspirations. &nbsp;Yet there appears to be a mismatch: Potential candidates (or &ldquo;the supply&rdquo;) are reporting challenges in the recruitment, integration, and retention phases, while the philanthropic organisations (or &ldquo;the demand&rdquo;) have had difficulties identifying these talents at the senior level.</span></p>
            <p><span><strong><span style="font-size: 12pt; color: #404040; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Defining the key characteristics of what makes a leader in this sector</span></strong></span></p>
            <p><span style="color: #404040; white-space: pre-wrap;">What has emerged as critical to bridge this talent gap &ndash; after a research study conducted by Asia Philanthropy Circle (APC), based on 20 high-level interviews with a mix of potential candidates and philanthropic organisations who represent the five South East Asian countries of Indonesia, Malaysia, the Philippines, Singapore, and Thailand &ndash; is the need to define an industry standard on what a good candidate for an executive management position in a philanthropic organisation looks like. &nbsp;With a focus on the executive directors (ED) and the chief executive officers (CEO) of these organisations, perspectives on both the problems and the corresponding recommendations are highlighted.</span></p>
            <p><span style="color: #404040; white-space: pre-wrap;">Some of these problems may not be surprising, but this study is one of the first concerted efforts in the region to systematically research and document findings, so as to generate impetus for collective action. &nbsp;Pay and compensation, as well as the availability of career development pathways for mid- to senior-level candidates, emerged as the key considerations for potential candidates. Overall the respondents also pointed to limited recruiting scope and board governance as issues, though the finding that recruiters often disregarded the non-profit experience of potential candidates might be interesting for some.</span></p>
            <p><span><strong><span style="font-size: 12pt; color: #404040; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Top 10 recommendations for organisation &amp; sector</span></strong></span></p>
            <p><span style="color: #404040; white-space: pre-wrap;">10 recommendations are proposed in response, and APC is committed to take the lead by crafting a &ldquo;competency framework&rdquo; with fellow industry stakeholders that will help set a benchmark for reference, and by catalysing an exchange or fellowship programme.</span></p>
            <p><span style="color: #404040; white-space: pre-wrap;">Some of other eight recommendations can be adopted by organisations internally and put to effect expeditiously &ndash; such as &ldquo;transition programmes&rdquo; for potential candidates making a jump from other sectors, the adoption of valuable approaches such as benchmarking HR practices with the SME sector, as well as strengthening the development of senior management &ndash; though others require sector-wide reforms and mind-set changes. &nbsp;Among these industry-wide recommendations include the sharing of case studies or &ldquo;good-in-class&rdquo; HR practices, the creation of a South East Asian database of executive pay and compensation, as well as advocacy for board improvements. The work involved in the individual and collective implementation of each recommendation is substantial, yet necessary.</span></p>
            <p><span><strong><span style="font-size: 12pt; color: #404040; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">The work begins: convening the sector to move things forward</span></strong></span></p>
            <p><span style="color: #404040; white-space: pre-wrap;">&ldquo;Bridging the talent gap&rdquo;, in other words, is but the first research brick that APC is laying for the philanthropy and social sector in South East Asia. &nbsp;With this first step, APC &ndash; informed by the interests of its members &ndash; is committed to mobilise the contributions of relevant and valued partners, to effectively create a sustained momentum to advance the level of professionalism in the sector so as to grow social impact in the region. &nbsp;Far too often, philanthropists and non-profit professionals in the region run ahead of their capacity to implement and fulfil their philanthropic aspirations, and in the process pay too little attention to the overall talent deficits in the sector.</span></p>
            <p><span style="color: #404040; white-space: pre-wrap;">A long-term goal, in this vein, is to actualise the vision &ndash; or truism &ndash; of empowering potential candidates and philanthropic organisations in the philanthropy and social sector to be matched more effectively, first and foremost by defining an industry standard on what a good ED or CEO looked like, and in addition, what a good organisation looked like. &nbsp;This will take time and effort, though the investment will be well worth it.</span></p>
            <p><span><em><span style="font-size: 12pt; color: #404040; white-space: pre-wrap;">*Jinyao is the researcher and author for the report: Bridging the Talent Gap, which will be launched soon with members and industry leaders.</span></em></span></p>
            <p><span style="color: #404040; white-space: pre-wrap;"><em>By Kwan Jinyao</em></span></p>',
        ],
        'file_path'        => 'uploads/learns/learn-01.png',
        'view'             => '0',
        'status'           => 'public',
        'highlight_status' => 'pinned',
        'type'             => '',
        'public_date'      => date( 'Y-m-d' ),
    ],
    [
        'id'               => '2',
        'fk_category_id'   => '1',
        'title_thai'       => 'The Global Landscape of Philanthropy report by WINGS',
        'title_english'    => 'The Global Landscape of Philanthropy report by WINGS',
        'content_thai'     => [
            '<p><span style="color: #404040;">From a description of various forms of individual giving to the growing importance of community philanthropy and structured, institutional giving, the current report is an effort to bring back the diversity of the field of philanthropy at the center of the debate, by drawing a comprehensive and provocative picture of current trends and challenges of the field. The report also raises some of the questions and issues most critical and central to its development &ndash; from technology and shrinking civic space to power dynamics within philanthropy practice and concepts, to the evolving role and form of philanthropy infrastructure.</span></p>
            <p><span style="color: #404040;">Through the voices of its some of its most prominent and wise advocates, the field of philanthropy appears in its complexity and multi-faceted reality.</span></p>
            <p><span style="color: #404040;">Readers will be able to understand the critical importance of individual giving, especially religious giving in certain parts of the world. They will read about the way technology is impacting philanthropic practices, creating the possibility of new methods of giving such as online giving, giving by SMS and crowdfunding.</span></p>
            <p><span style="color: #404040;">While the number of foundations is increasing, especially in Europe and in some countries in the southern hemisphere, most foundations remain very conservative in the area they support, giving to education, healthcare and social services. The report also highlights the characteristics of institutional giving, showing that generally speaking, foundations are more risk-averse than they say they are. </span></p>
            <p><span style="color: #404040;">Community foundations are a key part of this landscape: they have become a beacon of philanthropy everywhere, and have adapted to local requirements and circumstances, playing a wide variety of roles, from creating community to offering donor services.</span></p>
            <p><span style="color: #404040;">Another interesting finding of the report concerns the relationship between the for-profit and non-profit sectors. Increasingly, a hallmark of organizations working for social good is hybridity, with organizations with different legal forms adopting a variety of means of working. Consequently, notions of what constitutes &lsquo;philanthropy&rsquo; and &lsquo;philanthropists&rsquo; are broadening.</span></p>
            <p><span style="color: #404040;">Infrastructure organizations, their uneven distribution, their increasingly and necessarily changing role and mission, their business model are also discussed, highlighting the basic challenge for infrastructure organizations to demonstrate their value to the sector.</span></p>
            <p><span style="color: #404040;">By Muriel Asseraf</span></p>
            <p><em><span style="color: #404040;">This article first appeared on the WINGS website on 30 Jan 2018. </span></em></p>',
        ],
        'content_english'  => [
            '<p><span style="color: #404040;">From a description of various forms of individual giving to the growing importance of community philanthropy and structured, institutional giving, the current report is an effort to bring back the diversity of the field of philanthropy at the center of the debate, by drawing a comprehensive and provocative picture of current trends and challenges of the field. The report also raises some of the questions and issues most critical and central to its development &ndash; from technology and shrinking civic space to power dynamics within philanthropy practice and concepts, to the evolving role and form of philanthropy infrastructure.</span></p>
            <p><span style="color: #404040;">Through the voices of its some of its most prominent and wise advocates, the field of philanthropy appears in its complexity and multi-faceted reality.</span></p>
            <p><span style="color: #404040;">Readers will be able to understand the critical importance of individual giving, especially religious giving in certain parts of the world. They will read about the way technology is impacting philanthropic practices, creating the possibility of new methods of giving such as online giving, giving by SMS and crowdfunding.</span></p>
            <p><span style="color: #404040;">While the number of foundations is increasing, especially in Europe and in some countries in the southern hemisphere, most foundations remain very conservative in the area they support, giving to education, healthcare and social services. The report also highlights the characteristics of institutional giving, showing that generally speaking, foundations are more risk-averse than they say they are. </span></p>
            <p><span style="color: #404040;">Community foundations are a key part of this landscape: they have become a beacon of philanthropy everywhere, and have adapted to local requirements and circumstances, playing a wide variety of roles, from creating community to offering donor services.</span></p>
            <p><span style="color: #404040;">Another interesting finding of the report concerns the relationship between the for-profit and non-profit sectors. Increasingly, a hallmark of organizations working for social good is hybridity, with organizations with different legal forms adopting a variety of means of working. Consequently, notions of what constitutes &lsquo;philanthropy&rsquo; and &lsquo;philanthropists&rsquo; are broadening.</span></p>
            <p><span style="color: #404040;">Infrastructure organizations, their uneven distribution, their increasingly and necessarily changing role and mission, their business model are also discussed, highlighting the basic challenge for infrastructure organizations to demonstrate their value to the sector.</span></p>
            <p><span style="color: #404040;">By Muriel Asseraf</span></p>
            <p><em><span style="color: #404040;">This article first appeared on the WINGS website on 30 Jan 2018. </span></em></p>',
        ],
        'file_path'        => 'uploads/learns/learn-02.png',
        'view'             => '0',
        'status'           => 'public',
        'highlight_status' => 'pinned',
        'type'             => '',
        'public_date'      => date( 'Y-m-d' ),
    ],
    [
        'id'               => '3',
        'fk_category_id'   => '1',
        'title_thai'       => 'ASEAN Philanthropy Dialogue: How can Government and Philanthropy collaborate more effectively?',
        'title_english'    => 'ASEAN Philanthropy Dialogue: How can Government and Philanthropy collaborate more effectively?',
        'content_thai'     => [
            '<p><span>Philanthropists and government officials need to do more to build mutual trust and to align vision and strategies, in order to reap the synergies from public-philanthropic collaboration (PPC).</span></p>
            <p><span>Asia Philanthropy Circle (APC) members, ASEAN ministers and senior officials, and the ASEAN Secretariat discussed this and more at the inaugural ASEAN Philanthropy Dialogue in Singapore on 21 March 2018.</span></p>
            <p><span>Hosted by APC and part of the fringe events accompanying Singapore&rsquo;s ASEAN chairmanship, the Dialogue provided a platform for active discussion on PPC in growing social impact jointly.</span></p>
            <p><span>The benefits of PPC and the various modalities of its engagement were presented in the APC&rsquo;s Green Paper on Effective Public-Philanthropic Collaboration in ASEAN.&nbsp; In sharing its main findings, Laurence Lien, CEO of APC, iterated that a mindset shift was critical in helping philanthropists and governments understand each other&rsquo;s relative strengths and unique context in addressing increasingly complex social problems.</span></p>
            <p><span>Four APC members shared their experience in philanthropic projects that complement and supplement government initiatives, including Belinda Tanoto from the Tanoto Foundation, Kathleen Chew from YTL Foundation and Simon Flint from Dymon Capital (Asia).&nbsp; The projects showcased were Pelita Pendidikan in Indonesia, Global School Leaders Malaysia and the 1000 Days Fund in the region respectively.</span></p>
            <p><span>During the open and engaging discussion that followed, Mr Desmond Lee, Singapore Minister for Social and Family Development expressed his admiration for the showcased projects, yet raised caution for sustainability due to the constraints faced by philanthropists and governments.&nbsp; He opined that it would require extensive discussion and coordination between government and philanthropists if the aim is to scale projects for greater social impact.&nbsp; He also repeatedly assured that governments, and in his case, the Singapore government, remain open for collaboration opportunities.</span></p>
            <p><span>Dato&rsquo; Lim Jock Hoi, ASEAN Secretary-General, articulated his support for the dialogue and wishes for more in-depth exchanges in the future.</span></p>
            <p><span>Deputy Secretary General, Mr Vongthep Arthakaivalvatee, also signalled his support by saying that &ldquo;philanthropy should be encouraged to be a household term in ASEAN&rdquo;.</span></p>
            <p><span>Government delegates from the various countries were receptive to the idea of collaborating with philanthropists to complement the government&rsquo;s work.</span></p>
            <p><span>The session closed by APC Chairman Stanley Tan emphasising that philanthropists and governments can make partnership viable and effective in investing to make lives better and build capacity.&nbsp; He hoped that the Dialogue was just the beginning of greater impetus to forge the trust and understanding needed to spark new possibilities for cross-sectoral partnerships.</span></p>
            <p><em><span>by Atikah Amalina</span></em></p>',
        ],
        'content_english'  => [
            '<p><span>Philanthropists and government officials need to do more to build mutual trust and to align vision and strategies, in order to reap the synergies from public-philanthropic collaboration (PPC).</span></p>
            <p><span>Asia Philanthropy Circle (APC) members, ASEAN ministers and senior officials, and the ASEAN Secretariat discussed this and more at the inaugural ASEAN Philanthropy Dialogue in Singapore on 21 March 2018.</span></p>
            <p><span>Hosted by APC and part of the fringe events accompanying Singapore&rsquo;s ASEAN chairmanship, the Dialogue provided a platform for active discussion on PPC in growing social impact jointly.</span></p>
            <p><span>The benefits of PPC and the various modalities of its engagement were presented in the APC&rsquo;s Green Paper on Effective Public-Philanthropic Collaboration in ASEAN.&nbsp; In sharing its main findings, Laurence Lien, CEO of APC, iterated that a mindset shift was critical in helping philanthropists and governments understand each other&rsquo;s relative strengths and unique context in addressing increasingly complex social problems.</span></p>
            <p><span>Four APC members shared their experience in philanthropic projects that complement and supplement government initiatives, including Belinda Tanoto from the Tanoto Foundation, Kathleen Chew from YTL Foundation and Simon Flint from Dymon Capital (Asia).&nbsp; The projects showcased were Pelita Pendidikan in Indonesia, Global School Leaders Malaysia and the 1000 Days Fund in the region respectively.</span></p>
            <p><span>During the open and engaging discussion that followed, Mr Desmond Lee, Singapore Minister for Social and Family Development expressed his admiration for the showcased projects, yet raised caution for sustainability due to the constraints faced by philanthropists and governments.&nbsp; He opined that it would require extensive discussion and coordination between government and philanthropists if the aim is to scale projects for greater social impact.&nbsp; He also repeatedly assured that governments, and in his case, the Singapore government, remain open for collaboration opportunities.</span></p>
            <p><span>Dato&rsquo; Lim Jock Hoi, ASEAN Secretary-General, articulated his support for the dialogue and wishes for more in-depth exchanges in the future.</span></p>
            <p><span>Deputy Secretary General, Mr Vongthep Arthakaivalvatee, also signalled his support by saying that &ldquo;philanthropy should be encouraged to be a household term in ASEAN&rdquo;.</span></p>
            <p><span>Government delegates from the various countries were receptive to the idea of collaborating with philanthropists to complement the government&rsquo;s work.</span></p>
            <p><span>The session closed by APC Chairman Stanley Tan emphasising that philanthropists and governments can make partnership viable and effective in investing to make lives better and build capacity.&nbsp; He hoped that the Dialogue was just the beginning of greater impetus to forge the trust and understanding needed to spark new possibilities for cross-sectoral partnerships.</span></p>
            <p><em><span>by Atikah Amalina</span></em></p>',
        ],
        'file_path'        => 'uploads/learns/learn-03.jpg',
        'view'             => '0',
        'status'           => 'public',
        'highlight_status' => 'pinned',
        'type'             => '',
        'public_date'      => date( 'Y-m-d' ),
    ],
    [
        'id'               => '4',
        'fk_category_id'   => '1',
        'title_thai'       => 'Why a Green Paper on Effective Public-Philanthropic Collaboration in ASEAN?',
        'title_english'    => 'Why a Green Paper on Effective Public-Philanthropic Collaboration in ASEAN?',
        'content_thai'     => [
            '<p><span>As social problems becoming increasingly complex, APC believes that more can be done if governments and philanthropists work in concert. There is value in coming together to align goals and harness each other&rsquo;s unique strengths. This would leverage the collective intelligence and capacity for better social outcomes.</span></p>
            <p><span>The</span><a href="http://www.asiaphilanthropycircle.org/green-paper-on-effective-public-philanthropic-collaboration-in-asean/">
            <span> Green Paper on Effective Public-Philanthropic Collaboration in ASEAN</span></a><span> is a first attempt to draw attention to the benefits of governments and philanthropists working together for social good. It examines the current public-philanthropic landscape in ASEAN and suggests practical ways that governments and philanthropists can work together in the near to long term. The priority would be to continue sharing and exchanging ideas on various platforms to build trust and deepen understanding of each other.</span></p>
            <p><span>Drawing on insights from APC members and their organisations in their respective philanthropic journeys, the Green Paper emphasised that there is no one right way of collaborating. Multiple levels of engagement &ndash; from informal to formal, from low to high degrees of alignment, and from mere coordination to joint implementation &ndash; are possible. Depending on the circumstance, certain levels of engagement more appropriate than others. It is more important to appreciate each other&rsquo;s views and expectations in the given context to make the most of any collaboration.</span></p>
            <p><span>The </span><a href="http://www.asiaphilanthropycircle.org/green-paper-on-effective-public-philanthropic-collaboration-in-asean/">
            <span>Green Paper</span></a><span> was used as the basis for discussions at the inaugural ASEAN Philanthropy Dialogue (APD) held on 21 March 2018 at Swiss&ocirc;tel the Stamford, Singapore, which brought together government leaders and philanthropists from ASEAN. Presented by APC CEO, Laurence Lien, the Green Paper stimulated dialogue on their respective concerns, challenges faced and aspirations for greater social impact. Both sides welcomed the findings of the Green Paper and agreed to explore actionable ideas to advance greater PPCs.</span></p>',
        ],
        'content_english'  => [
            '<p><span>As social problems becoming increasingly complex, APC believes that more can be done if governments and philanthropists work in concert. There is value in coming together to align goals and harness each other&rsquo;s unique strengths. This would leverage the collective intelligence and capacity for better social outcomes.</span></p>
            <p><span>The</span><a href="http://www.asiaphilanthropycircle.org/green-paper-on-effective-public-philanthropic-collaboration-in-asean/">
            <span> Green Paper on Effective Public-Philanthropic Collaboration in ASEAN</span></a><span> is a first attempt to draw attention to the benefits of governments and philanthropists working together for social good. It examines the current public-philanthropic landscape in ASEAN and suggests practical ways that governments and philanthropists can work together in the near to long term. The priority would be to continue sharing and exchanging ideas on various platforms to build trust and deepen understanding of each other.</span></p>
            <p><span>Drawing on insights from APC members and their organisations in their respective philanthropic journeys, the Green Paper emphasised that there is no one right way of collaborating. Multiple levels of engagement &ndash; from informal to formal, from low to high degrees of alignment, and from mere coordination to joint implementation &ndash; are possible. Depending on the circumstance, certain levels of engagement more appropriate than others. It is more important to appreciate each other&rsquo;s views and expectations in the given context to make the most of any collaboration.</span></p>
            <p><span>The </span><a href="http://www.asiaphilanthropycircle.org/green-paper-on-effective-public-philanthropic-collaboration-in-asean/">
            <span>Green Paper</span></a><span> was used as the basis for discussions at the inaugural ASEAN Philanthropy Dialogue (APD) held on 21 March 2018 at Swiss&ocirc;tel the Stamford, Singapore, which brought together government leaders and philanthropists from ASEAN. Presented by APC CEO, Laurence Lien, the Green Paper stimulated dialogue on their respective concerns, challenges faced and aspirations for greater social impact. Both sides welcomed the findings of the Green Paper and agreed to explore actionable ideas to advance greater PPCs.</span></p>',
        ],
        'file_path'        => 'uploads/learns/learn-04.jpg',
        'view'             => '0',
        'status'           => 'public',
        'highlight_status' => 'pinned',
        'type'             => '',
        'public_date'      => date( 'Y-m-d' ),
    ],
    [
        'id'               => '5',
        'fk_category_id'   => '1',
        'title_thai'       => 'How is Asia faring in the Global Philanthropy Report?',
        'title_english'    => 'How is Asia faring in the Global Philanthropy Report?',
        'content_thai'     => [
            '<p><em><span>by Anjali Shivananda</span></em></p>
            <p><span>The </span><a href="https://cpl.hks.harvard.edu/node/1124122/e?admin_panel=1">
            <span>Global Philanthropy Report</span></a><span> released by Harvard Kennedy School&rsquo;s Hauser Institute for Civil Society, and funded by UBS and Ford Foundation, aims to understand the magnitude, vitality and impact of global institutional philanthropy.&nbsp; The study identified 260,000 foundations in 38 countries (+ Hong Kong) and deals with various elements of philanthropy such as the global scale of foundations, its age, classification, financial resources, their priorities and operational approaches.</span></p>
            <p><span>One of the findings that stood out in the report is the age of the sector, where three-quarters of the foundations studied being younger than 25 years old.&nbsp; Viewing this fact from the Asian perspective, the Centre for Asian Philanthropy and Society in the Doing Good Index, 2018 has stated that the median age of Social Delivery Organisations in Asia is 14 years.&nbsp; The relative youth of the sector can be attributed to the increase in its individual wealth due to the regions tremendous economic growth which has led to more individuals venturing into philanthropy.&nbsp; For example, the number of Chinese billionaires grew from three in 2004 to 568 in 2016, a 200 times increase within 12 years.</span><a href="http://www.asiaphilanthropycircle.org/how-is-asia-faring-in-the-global-philanthropy-report/#_ftn1">
            <span>[1]</span></a></p>
            <p><span>By 2015, eight percent of the world&rsquo;s super-high-net-worth individuals with more than USD 50 million in assets were in China </span>
            <span>2</span><span>.&nbsp; Apart from the increase in individual wealth, many philanthropists grew up at a time when the region was largely poor, this along with the personal desire to enact positive change in the society coupled with humble upbringings have been regarded as the main drivers of philanthropy in Asia.&nbsp; Considering this trend continues, the social and economic impact due to philanthropy is going to be more significant.</span></p>
            <p><a href="http://www.asiaphilanthropycircle.org/how-is-asia-faring-in-the-global-philanthropy-report/#_ftnref1">
            <span>[1]</span></a><span> Hurun Global Rich List 2016, Huron Institute, 2016 mentioned in The Chinese Collectivist Model of Charity. Stanford Social Innovation Review. 2017.</span></p>
            <p><span>2</span><span> Global Wealth Report 2015, Credit Suisse, 2015 mentioned in The Chinese Collectivist Model of Charity Stanford Social Innovation Review.</span></p>
            <img src="../public/storage/uploads/learns/learn-05-1.png">
            <p><span>Collaboration among foundations has been emphasised to foster the increase of capital in the region, and also to encourage&nbsp; a platform to exchange views and insights among philanthropists and foundations to scale impact.&nbsp; The global philanthropy report highlighted that 58 per cent of the foundations identified for the study do not collaborate with one another even though they might be working towards the same objectives.&nbsp; This trend exists despite various conversations within the philanthropy sector on the need for an efficient convergent mechanism that sustains through time.</span></p>
            <p><span>The report findings showed that an annual investment of USD 5-7 trillion is required to satisfy the UN Sustainable Development Goals, and collaborative approach is one of the suitable methods to achieve this objective.&nbsp; In a study conducted by Asia Centre for Social Entrepreneurship and Philanthropy, the findings of the report concluded that collaboration was limited among foundations in Asia.&nbsp; The Myanmar-based institutions interviewed for the study worked independently, although there were some collaborations between foundations in China and Singapore.&nbsp; Despite this, the report concluded stating there is scope for positive trend towards collaboration among non-profit organisations, foundations and international non-governmental organisations in the region.</span></p>
            <p><span>Although collaboration among Asian countries has not reached the desired level, collective impact among Chinese philanthropists is making news.&nbsp; For example, Jack Ma, the founder of Alibaba, focuses on environment sustainability as part of his philanthropic activity, but unlike many western organisations, he did not establish a foundation in his name but rather founded a joint project called Paradise International Foundation along with like-minded people.&nbsp; This example can be validated by other philanthropists in China, where the ratio of individual donations is on a decline and on the contrast collective donations have witnessed a rise.</span></p>
            <img src="../public/storage/uploads/learns/learn-05-2.png">
            <p><span>Asia has been under represented in the report, primarily due to the nascent sector and lack of data forthcoming in this part of the world.&nbsp; However, with the rapid growth of the economy and increase in individual wealth, philanthropy in the region is set to grow and setting our benchmark and reference against a global standard will be helpful in the sector&rsquo;s continued development.</span></p>',
        ],
        'content_english'  => [
            '<p><em><span>by Anjali Shivananda</span></em></p>
            <p><span>The </span><a href="https://cpl.hks.harvard.edu/node/1124122/e?admin_panel=1">
            <span>Global Philanthropy Report</span></a><span> released by Harvard Kennedy School&rsquo;s Hauser Institute for Civil Society, and funded by UBS and Ford Foundation, aims to understand the magnitude, vitality and impact of global institutional philanthropy.&nbsp; The study identified 260,000 foundations in 38 countries (+ Hong Kong) and deals with various elements of philanthropy such as the global scale of foundations, its age, classification, financial resources, their priorities and operational approaches.</span></p>
            <p><span>One of the findings that stood out in the report is the age of the sector, where three-quarters of the foundations studied being younger than 25 years old.&nbsp; Viewing this fact from the Asian perspective, the Centre for Asian Philanthropy and Society in the Doing Good Index, 2018 has stated that the median age of Social Delivery Organisations in Asia is 14 years.&nbsp; The relative youth of the sector can be attributed to the increase in its individual wealth due to the regions tremendous economic growth which has led to more individuals venturing into philanthropy.&nbsp; For example, the number of Chinese billionaires grew from three in 2004 to 568 in 2016, a 200 times increase within 12 years.</span><a href="http://www.asiaphilanthropycircle.org/how-is-asia-faring-in-the-global-philanthropy-report/#_ftn1">
            <span>[1]</span></a></p>
            <p><span>By 2015, eight percent of the world&rsquo;s super-high-net-worth individuals with more than USD 50 million in assets were in China </span>
            <span>2</span><span>.&nbsp; Apart from the increase in individual wealth, many philanthropists grew up at a time when the region was largely poor, this along with the personal desire to enact positive change in the society coupled with humble upbringings have been regarded as the main drivers of philanthropy in Asia.&nbsp; Considering this trend continues, the social and economic impact due to philanthropy is going to be more significant.</span></p>
            <p><a href="http://www.asiaphilanthropycircle.org/how-is-asia-faring-in-the-global-philanthropy-report/#_ftnref1">
            <span>[1]</span></a><span> Hurun Global Rich List 2016, Huron Institute, 2016 mentioned in The Chinese Collectivist Model of Charity. Stanford Social Innovation Review. 2017.</span></p>
            <p><span>2</span><span> Global Wealth Report 2015, Credit Suisse, 2015 mentioned in The Chinese Collectivist Model of Charity Stanford Social Innovation Review.</span></p>
            <img src="../public/storage/uploads/learns/learn-05-1.png">
            <p><span>Collaboration among foundations has been emphasised to foster the increase of capital in the region, and also to encourage&nbsp; a platform to exchange views and insights among philanthropists and foundations to scale impact.&nbsp; The global philanthropy report highlighted that 58 per cent of the foundations identified for the study do not collaborate with one another even though they might be working towards the same objectives.&nbsp; This trend exists despite various conversations within the philanthropy sector on the need for an efficient convergent mechanism that sustains through time.</span></p>
            <p><span>The report findings showed that an annual investment of USD 5-7 trillion is required to satisfy the UN Sustainable Development Goals, and collaborative approach is one of the suitable methods to achieve this objective.&nbsp; In a study conducted by Asia Centre for Social Entrepreneurship and Philanthropy, the findings of the report concluded that collaboration was limited among foundations in Asia.&nbsp; The Myanmar-based institutions interviewed for the study worked independently, although there were some collaborations between foundations in China and Singapore.&nbsp; Despite this, the report concluded stating there is scope for positive trend towards collaboration among non-profit organisations, foundations and international non-governmental organisations in the region.</span></p>
            <p><span>Although collaboration among Asian countries has not reached the desired level, collective impact among Chinese philanthropists is making news.&nbsp; For example, Jack Ma, the founder of Alibaba, focuses on environment sustainability as part of his philanthropic activity, but unlike many western organisations, he did not establish a foundation in his name but rather founded a joint project called Paradise International Foundation along with like-minded people.&nbsp; This example can be validated by other philanthropists in China, where the ratio of individual donations is on a decline and on the contrast collective donations have witnessed a rise.</span></p>
            <img src="../public/storage/uploads/learns/learn-05-2.png">
            <p><span>Asia has been under represented in the report, primarily due to the nascent sector and lack of data forthcoming in this part of the world.&nbsp; However, with the rapid growth of the economy and increase in individual wealth, philanthropy in the region is set to grow and setting our benchmark and reference against a global standard will be helpful in the sector&rsquo;s continued development.</span></p>',
        ],
        'file_path'        => 'uploads/learns/learn-05.png',
        'view'             => '0',
        'status'           => 'public',
        'highlight_status' => 'pinned',
        'type'             => '',
        'public_date'      => date( 'Y-m-d' ),
    ],
    [
        'id'               => '6',
        'fk_category_id'   => '1',
        'title_thai'       => 'Does Collective Impact really work? Results from 25 case studies',
        'title_english'    => 'Does Collective Impact really work? Results from 25 case studies',
        'content_thai'     => [
            '<p><strong><span>The idea of collective impact is quite central to APC and our work but what is at stake is figuring out how to make it work effectively.&nbsp; Given that and with our members in mind, we referred to a </span></strong><a href="https://www.strivetogether.org/wp-content/uploads/2018/05/CI-Study-Report_May-2018.pdf"><strong><span style="font-size: 12.0pt; line-height: 115%; font-family: Roboto; color: #367588;">recent study conducted by Spark Policy Institute and ORS Impact on 25 such cases</span></strong></a><strong><span>, outlining what are the key lessons in making collective impact work; what kind of projects they are good for, what are the critical ingredients; what can be applicable for us.</span></strong></p>
            <img src="../public/storage/uploads/learns/learn-06.jpg"/>
            <p><strong><span>Collective Impact Study:</span></strong></p>
            <p><span>It has been about seven years since John Kanla Mark Kramer first used the term &ldquo;collective impact&rdquo; as an approach for solving social problems at scale.&nbsp; As philanthropists realise the complexity of social and environmental problems, more are looking towards holistic approaches that can address these issues at a system level.&nbsp; &ldquo;Collective impact&rdquo; was defined as the commitment of a group of important actors from different sectors that align with a common agenda to solve a specific social problem.&nbsp; These initiatives are distinct from other forms of collaboration in their cross-sector composition and their implementation of the given conditions necessary for population-level change.&nbsp; Conditions include <strong>a common agenda, shared measurement, mutually reinforcing activities, continuous communication and backbone support</strong>.</span></p>
            <p><span>Seven years later, the Spark Policy Institute and ORS Impact conducted a study to fully understand the <strong>effects and scale of successful collective impact</strong>, as well as explain the relationship between collective impact approaches, their systems and the resulting population changes.&nbsp; Utilising process tracing to determine the degree in which collective impact contributed to making population-level change and solve problems that initiatives had set out to address, the study assessed the inferential strength of the hypothesised relationships across 25 study sites.</span></p>
            <p><span>Despite the fact that study sites did not have an explicit focus and/or attend deeply to issues of representation and inclusion, they are achieving impact that could be described as equity-focused, in that better systems and outcomes should benefit high-risk populations.&nbsp; Hence, strong implementation of equity intent and actions are assumed to lead to achievement of equitable systems and population changes.</span></p>
            <p><strong><span>Four Implications and Applications for Successful Collective Impact:</span></strong></p>
            <p><span>To ensure the success of future APC projects, details from these key implications for success can be extracted and translated into existing projects so that not only social problems are tackled at scale, but also, ensure that equity and change is achieved.</span></p>
            <h3><strong><span>collective impact is a long-term proposition</span></strong></h3>
            <p><span>The first implication is that collective impact is a long-term proposition and that it takes time to lay a strong foundation.&nbsp; Recognising that the proposition is worth the wait, taking time to develop a strong common agenda and finding a credible, skilled and ready backbone to maintain an effective collaborative environment focused on systems change are specific steps that constitutes laying a strong foundation at the start of a collaboration.</span></p>
            <h3><strong><span>there is no one path: systems change can take place in many different forms</span></strong></h3>
            <p><span>Secondly, systems change can take place in many different forms.&nbsp; In order to do so, one must understand that a wide variety of systems change plays a valuable role towards population changes.&nbsp; Ultimately, acknowledging that systems change is iterative and not fully predictable helps one to understand that there is no one path or simple pattern that can be easily replicated.</span></p>
            <h3><strong><span>representation, inclusion and empowerment is integral with community stakeholders</span></strong></h3>
            <p><span>The next step is to remember that equity goes beyond achieving a set of outcomes; it requires intent, shifting power, and meaningful inclusion along with targeted problem definition and action.&nbsp; For collective impact to achieve its full and lasting potential, it is integral to re-think the systems and structures that produce inequity to begin with.&nbsp; Hence it is necessary to bring together community stakeholders to ensure that equity sites are intentional about representation, inclusion and empowerment.</span></p>
            <h3><strong><span>it&rsquo;s OK to be unconventional</span></strong></h3>
            <p><span>The final implication that was concluded is that collective impact initiatives take on different roles in driving change and that it is important to be open to different routes to making a difference.&nbsp; The collective impact approach proves that in order to inspire change, one has to be adaptable and take an unconventional route that includes leveraging existing regulations and conditions to make a difference in a diverse set of circumstances.</span></p>
            <p><strong><span>Key Lessons for APC Members</span></strong></p>
            <p><span>When the collective impact approach meaningfully contributes to documented population changes, systems change occurs to support collective impact common agendas and reinforces the importance of the conditions to provide a better understanding of what equity approaches and outcomes can look like.&nbsp; Through leveraging the concluding statements from the study, philanthropists from different sectors are able to come together with different knowledge and expertise and tackle a social problem collectively at scale.</span></p>
            <p><span>The key to success appears to lie in actions and systems changes across the initiatives that naturally focus on high-need populations experiencing inequities.&nbsp; Thus, their programmatic and policy solutions have a disproportionate benefit to those groups.&nbsp; As a result, stronger implementation of equity intent and actions can lead to some achievement of equitable systems and population changes, with stronger results among those with the strongest equity focus.</span></p>
            <p><strong><em><span>TL:DR &ndash; start engaging in a high-risk, patient and deeply thoughtful collaborative project with your APC partners today!</span></em></strong></p>
            <p><strong><em><span>By Valentina Ko &amp; Stacey Choe</span></em></strong></p>',
        ],
        'content_english'  => [
            '<p><strong><span>The idea of collective impact is quite central to APC and our work but what is at stake is figuring out how to make it work effectively.&nbsp; Given that and with our members in mind, we referred to a </span></strong><a href="https://www.strivetogether.org/wp-content/uploads/2018/05/CI-Study-Report_May-2018.pdf"><strong><span style="font-size: 12.0pt; line-height: 115%; font-family: Roboto; color: #367588;">recent study conducted by Spark Policy Institute and ORS Impact on 25 such cases</span></strong></a><strong><span>, outlining what are the key lessons in making collective impact work; what kind of projects they are good for, what are the critical ingredients; what can be applicable for us.</span></strong></p>
            <img src="../public/storage/uploads/learns/learn-06.jpg"/>
            <p><strong><span>Collective Impact Study:</span></strong></p>
            <p><span>It has been about seven years since John Kanla Mark Kramer first used the term &ldquo;collective impact&rdquo; as an approach for solving social problems at scale.&nbsp; As philanthropists realise the complexity of social and environmental problems, more are looking towards holistic approaches that can address these issues at a system level.&nbsp; &ldquo;Collective impact&rdquo; was defined as the commitment of a group of important actors from different sectors that align with a common agenda to solve a specific social problem.&nbsp; These initiatives are distinct from other forms of collaboration in their cross-sector composition and their implementation of the given conditions necessary for population-level change.&nbsp; Conditions include <strong>a common agenda, shared measurement, mutually reinforcing activities, continuous communication and backbone support</strong>.</span></p>
            <p><span>Seven years later, the Spark Policy Institute and ORS Impact conducted a study to fully understand the <strong>effects and scale of successful collective impact</strong>, as well as explain the relationship between collective impact approaches, their systems and the resulting population changes.&nbsp; Utilising process tracing to determine the degree in which collective impact contributed to making population-level change and solve problems that initiatives had set out to address, the study assessed the inferential strength of the hypothesised relationships across 25 study sites.</span></p>
            <p><span>Despite the fact that study sites did not have an explicit focus and/or attend deeply to issues of representation and inclusion, they are achieving impact that could be described as equity-focused, in that better systems and outcomes should benefit high-risk populations.&nbsp; Hence, strong implementation of equity intent and actions are assumed to lead to achievement of equitable systems and population changes.</span></p>
            <p><strong><span>Four Implications and Applications for Successful Collective Impact:</span></strong></p>
            <p><span>To ensure the success of future APC projects, details from these key implications for success can be extracted and translated into existing projects so that not only social problems are tackled at scale, but also, ensure that equity and change is achieved.</span></p>
            <h3><strong><span>collective impact is a long-term proposition</span></strong></h3>
            <p><span>The first implication is that collective impact is a long-term proposition and that it takes time to lay a strong foundation.&nbsp; Recognising that the proposition is worth the wait, taking time to develop a strong common agenda and finding a credible, skilled and ready backbone to maintain an effective collaborative environment focused on systems change are specific steps that constitutes laying a strong foundation at the start of a collaboration.</span></p>
            <h3><strong><span>there is no one path: systems change can take place in many different forms</span></strong></h3>
            <p><span>Secondly, systems change can take place in many different forms.&nbsp; In order to do so, one must understand that a wide variety of systems change plays a valuable role towards population changes.&nbsp; Ultimately, acknowledging that systems change is iterative and not fully predictable helps one to understand that there is no one path or simple pattern that can be easily replicated.</span></p>
            <h3><strong><span>representation, inclusion and empowerment is integral with community stakeholders</span></strong></h3>
            <p><span>The next step is to remember that equity goes beyond achieving a set of outcomes; it requires intent, shifting power, and meaningful inclusion along with targeted problem definition and action.&nbsp; For collective impact to achieve its full and lasting potential, it is integral to re-think the systems and structures that produce inequity to begin with.&nbsp; Hence it is necessary to bring together community stakeholders to ensure that equity sites are intentional about representation, inclusion and empowerment.</span></p>
            <h3><strong><span>it&rsquo;s OK to be unconventional</span></strong></h3>
            <p><span>The final implication that was concluded is that collective impact initiatives take on different roles in driving change and that it is important to be open to different routes to making a difference.&nbsp; The collective impact approach proves that in order to inspire change, one has to be adaptable and take an unconventional route that includes leveraging existing regulations and conditions to make a difference in a diverse set of circumstances.</span></p>
            <p><strong><span>Key Lessons for APC Members</span></strong></p>
            <p><span>When the collective impact approach meaningfully contributes to documented population changes, systems change occurs to support collective impact common agendas and reinforces the importance of the conditions to provide a better understanding of what equity approaches and outcomes can look like.&nbsp; Through leveraging the concluding statements from the study, philanthropists from different sectors are able to come together with different knowledge and expertise and tackle a social problem collectively at scale.</span></p>
            <p><span>The key to success appears to lie in actions and systems changes across the initiatives that naturally focus on high-need populations experiencing inequities.&nbsp; Thus, their programmatic and policy solutions have a disproportionate benefit to those groups.&nbsp; As a result, stronger implementation of equity intent and actions can lead to some achievement of equitable systems and population changes, with stronger results among those with the strongest equity focus.</span></p>
            <p><strong><em><span>TL:DR &ndash; start engaging in a high-risk, patient and deeply thoughtful collaborative project with your APC partners today!</span></em></strong></p>
            <p><strong><em><span>By Valentina Ko &amp; Stacey Choe</span></em></strong></p>',
        ],
        'file_path'        => 'uploads/learns/learn-06.jpg',
        'view'             => '0',
        'status'           => 'public',
        'highlight_status' => 'pinned',
        'type'             => '',
        'public_date'      => date( 'Y-m-d' ),
    ],
];